[serviceweaver]
binary = "./bookinfo-serviceweaver"
rollout = "5m"

[single]
listeners.productpage = {address = "localhost:12345"}

[multi]
listeners.productpage = {address = "localhost:12345"}

[kube]
namespace = "default"
listeners.productpage = { public = true }